[package]
name = "aati"
description = "Minimal package manager written in Rust."
authors = ["Husayn Haras <husayn@dnmx.org>"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/hharas/aati"
documentation = "https://github.com/hharas/aati/blob/master/README.md"
version = "0.10.5"
edition = "2021"

[dependencies]
ascii = "1.1.0"
colored = "2.0.0"
dirs = "5.0.0"
hex = "0.4.3"
humansize = "2.1.3"
lz4 = "1.24.0"
ring = "0.16.20"
serde = { version = "1.0.159", features = ["derive"] }
tar = "0.4.38"
tiny_http = "0.12.0"
toml = "0.7.3"
ureq = "2.6.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
