[package]
name = "aati"
readme = "README.md"
license = "GPL-3.0-only"
version = "0.4.1"
edition = "2021"

[dependencies]
colored = "2.0.0"
dirs = "5.0.0"
hex = "0.4.3"
humansize = "2.1.3"
lz4 = "1.24.0"
ring = "0.16.20"
serde = { version = "1.0.159", features = ["derive"] }
toml = "0.7.3"
ureq = "2.6.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
